import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//! Next JS inbuilt script component 
import Script from 'next/script'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, Geek Coding blogs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainNav}>
        <ul>
          <li>Home</li>
          <li>about</li>
          <li>Blog</li>
          <li>Contact</li>
        </ul>
      </nav>
      {/* To load a third-party script in a single route, import next/script and include the script directly in your page component: */}
      {/* The script will only be fetched and executed when this specific page is loaded on the browser. */}
      {/* lazy load */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          GeCode
        </h1>

        <p className={styles.description}>
          A Special blog dedicated to all the coders ensuring
          there time management by providing optimal solutions for plethoric bugs
        </p>

        <div className="blogs">
          <div className="blogItem">
            <h2>Popular Blogs</h2>
            <h3>How to learn javascript in 2022</h3>
            <p>
              Javascript is a language of the internet. Every browser in the world are fused with Javascript
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2022</h3>
            <p>
              Javascript is a language of the internet. Every browser in the world are fused with Javascript
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2022</h3>
            <p>
              Javascript is a language of the internet. Every browser in the world are fused with Javascript
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
